spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa-in-action
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true
